### ISSUE TITLE
模型支持label标注到父类目的吗？

### ISSUE THREAD

**Issue by liqunhit** [RandolphVI/Hierarchical-Multi-Label-Text-Classification#1]
非常棒的工作，赞！
这里请教有一个问题，训练集（测试集）里，是否支持样本的label只标注到父节点的样本？比如类目是四级，但是存在部分样本只标注到了二级。

**Comment by liqunhit** [comment]
补充：人工定义的类目体系是否每个节点的层级都是一样的？比如有些只到二级，有些到三级。这样可以吗？

**Comment by RandolphVI** [comment]
@liqunhit 

很好的问题，现目前解决的主要还是人工定义的类目体系是规定统一的，即记录均包含四级，不存在一部分标记到四级，另一部分仅标记到二级。

对于你阐述的问题，有几个解决的方案：
1. 对仅含有二级标签的数据进行标签扩充，例如给定这些数据三、四级的标签为“unkown”（全新的一个类别），在后续模型训练预测上代码运行不存在不影响，在进行指定各个层级的标签预测时候，先通过预测数据后处理之后再进行评价指标运算。
2. 去除仅标记到二级标签、或者仅标记到三级标签的数据。
3. 使用网络权重迁移实现。即先对仅标记到二级标签的数据进行模型训练，模型训练完毕之后的网络参数迁移传递到给仅标记到三级标签的数据进行模型训练，以此类推（这个方法自然工作量比较大）。当然也可以分离数据，对标记到不同层级的数据进行分别网络训练，指标评价的时候也通过训练好的不同网络预测即可。

**Comment by liqunhit** [comment]
明白了，非常感谢回复。
另外还有个问题请教下，咱们这里文本的表示为啥用的是bilstm，有实验过BERT吗？

**Comment by RandolphVI** [comment]
@liqunhit 

Bi-LSTM 我觉得已经够了，整体的模型的参数其实很大了，如果要考虑使用 BERT，成本太高。

**Comment by liqunhit** [comment]
使用BERT+FLAT分类（不做层次分类），有对比过效果吗？

**Comment by RandolphVI** [comment]
@liqunhit 

暂时没有尝试过

**Comment by liqunhit** [comment]
好的，非常感谢回复。
