### ISSUE TITLE
Raw Patent Dataset

### ISSUE THREAD

**Issue by XinyiZ001** [RandolphVI/Hierarchical-Multi-Label-Text-Classification#11]
Is it possible for you to provide the raw patent dataset link so that we can analyze the inner relationship within the hierarchical labels? Since we cannot extract a clear hierarchical label relationship from your processed data.

Thanks!

**Comment by RandolphVI** [comment]
The raw patent dataset was crawled down by our lab, so the dataset doesn't belong to me personally. In addition, as for the raw patent dataset, our lab has the idea of publishing papers about the patent dataset, so the raw patent dataset cannot be provided now.

**Comment by XinyiZ001** [comment]
Quite thanks for your reply!
