### ISSUE TITLE
why highway is used in producing global prediction?

### ISSUE THREAD

**Issue by coderbyr** [RandolphVI/Hierarchical-Multi-Label-Text-Classification#12]
`       

    #Fully Connected Layer    
    self.fc_out = _fc_layer(self.ham_out)
    # Highway Layer
        with tf.name_scope("highway"):
            self.highway = _highway_layer(self.fc_out, self.fc_out.get_shape()[1], num_layers=1, bias=0)`
In the paper, to get global predicts, one should use avg pooling operation to reduce dimension, while in the code, firstly, one use a fc layer, and then use highway to enhance the representation, I'm a little confused here  by the code, can u explain why?

**Comment by RandolphVI** [comment]
@coderbyr 

It's used for the future version. In the future work, **Highway Layer** will be used to alleviate the gradient problem, and other model updates and code updates will be git updated directly, so it will be somewhat different from the original version in the paper.

**Comment by coderbyr** [comment]
> @coderbyr
> 
> It's used for the future version. In the future work, **Highway Layer** will be used to alleviate the gradient problem, and other model updates and code updates will be git updated directly, so it will be somewhat different from the original version in the paper.

ok, so we can also follow what the paper says to reproduce the result? Is Highway Layer performing better?

**Comment by RandolphVI** [comment]
@coderbyr 

You can use the version of the paper (remove the Highway Layer) which can also reproduce the result. And yes, according to the experiment, Highway Layer can slightly improve the performance.
