### ISSUE TITLE
您好，请教一下数据的问题

### ISSUE THREAD

**Issue by JayJQK** [RandolphVI/Hierarchical-Multi-Label-Text-Classification#2]
您好，看了您的代码之后我有两个疑问：
1.数据中的title具体指的是什么意思，我做我自己的数据的时候可不可以不加title
2.如果我使用自己的数据是不是需要准备两个数据文件，一个是content.txt，另一个是我自己写好格式的json，您这里是不是没有生成json文件的程序，感谢！

**Comment by RandolphVI** [comment]
@JayJQK 

1. 可以不用加 `title`，这个字段只是我的数据里面有的，代码实际只用了 `abstract` 字段中的部分。
2. 因为前提是需要通过 `content.txt` 和你自己写好格式的 .json 文件，然后用 `genism` 生成你对应数据语料库的 Word2vec 模型文件，作为模型的输入（虽然也可以不用，可以采用随机初始化词向量列表）。我这边的 `data_helpers.py` 的代码中略去了先前我预处理生成 .json 文件的 script。

**Comment by JayJQK** [comment]
@RandolphVI 
十分感谢

**Comment by JayJQK** [comment]
你好，我在看您的test代码，不明白为什么测试集还要进行训练（也有loss），除此之外，我还想写一个predict函数，通过test代码不太好写。

**Comment by RandolphVI** [comment]
@JayJQK 

`test.py` 就是用来预测用的，没有进行训练。因为你在预测的时候，同样也可以计算网络在 test 测试集上的指标和 loss 罢了。不太明白你后面想再写一个 predict 函数的意思，`test.py` 文件已经就是可以 predict 了，你可以仔细看一下。
